name: simply_news
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ^3.24.3

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  data:
    path: packages/data
  domain:
    path: packages/domain
  flutter:
    sdk: flutter
  http: ^1.3.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  provider: ^6.1.2
  share_plus: ^10.0.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
