name: simply_news
description: "A text-focused news app fetching data from NewsAPI.org, with favorites, offline storage, and real-time updates."
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ^3.29.0

dependencies:
  clock: ^1.1.2
  collection: ^1.19.1
  data:
    path: packages/data
  domain:
    path: packages/domain
  firebase_core: ^3.12.0
  firebase_remote_config: ^5.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  path: ^1.9.1
  provider: ^6.1.2
  share_plus: ^10.1.4
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
