name: simply_news
description: "A text-focused news app fetching data from NewsAPI.org, with favorites, offline storage, and real-time updates."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ^3.27.4

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  data:
    path: packages/data
  domain:
    path: packages/domain
  firebase_core: ^3.11.0
  firebase_remote_config: ^5.4.0
  flutter:
    sdk: flutter
  http: ^1.3.0
  path: ^1.9.0
  provider: ^6.1.2
  share_plus: ^10.0.2
  sqflite: ^2.3.3+1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
