// Mocks generated by Mockito 5.4.5 from annotations
// in data/test/manager/settings_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:domain/src/model/settings_data.dart' as _i2;
import 'package:domain/src/repository/settings_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettingsData_0 extends _i1.SmartFake implements _i2.SettingsData {
  _FakeSettingsData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i3.SettingsRepository {
  @override
  _i4.Stream<_i2.SettingsData> get changes =>
      (super.noSuchMethod(
            Invocation.getter(#changes),
            returnValue: _i4.Stream<_i2.SettingsData>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.SettingsData>.empty(),
          )
          as _i4.Stream<_i2.SettingsData>);

  @override
  _i4.Future<_i2.SettingsData> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i4.Future<_i2.SettingsData>.value(
              _FakeSettingsData_0(this, Invocation.method(#get, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SettingsData>.value(
              _FakeSettingsData_0(this, Invocation.method(#get, [])),
            ),
          )
          as _i4.Future<_i2.SettingsData>);

  @override
  _i4.Future<void> update(_i3.UpdateSettings? updateSettings) =>
      (super.noSuchMethod(
            Invocation.method(#update, [updateSettings]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
